#Scenario
#You’re given event data from devices. Each row represents one event generated by a device at a specific time and location.

import pandas as pd

df = pd.DataFrame({
    "device_id": ["d1","d2","d1","d3","d2","d2","d4", None, "d4"],
    "location_id": ["l1","l1","l1","l2","l1","l1","l2","l2","l2"],
    "event_time": [
        "2026-02-09T08:15:00Z",
        "2026-02-09T09:00:00Z",
        "2026-02-09T10:30:00Z",
        "2026-02-09T11:45:00Z",
        "2026-02-10T00:10:00Z",
        "2026-02-10T08:00:00Z",
        "2026-02-10T09:30:00Z",
        "2026-02-10T10:00:00Z",
        None
    ]
})


#Your Task
#Write pandas code that produces a DataFrame with:
#day (YYYY-MM-DD)
#location_id
#event_count → total number of events per location per day

#Rules
#Ignore rows where device_id or event_time is null
#Convert event_time to a proper datetime
#Group by day + location_id
#Sort output by day, then location_id

import pandas as pd 

df["event_time"] = pd.to_datetime(df["event_time"], utc=True, errors="coerce")


mask = (
  (df["device_id"].notna()) & 
  (df["event_time"].notna()) 
)

df_clean = df[mask].copy()

df_clean["day"] = df_clean["event_time"].dt.strftime("%Y-%m-%d")

df_summary = (
  df_clean 
  .groupby(["day", "location_id"], as_index=False)
  .agg(
    event_count=("event_time", "count"))
  .sort_values(["day", "location_id"])
  .reset_index(drop=True)
)



df_clean, df_summary 
    
  

