#Scenario
#You’re analysing device activity. Each row represents an event generated by a device.

import pandas as pd

df = pd.DataFrame({
    "device_id": ["d1","d1","d2","d3","d2","d4","d4", None],
    "location_id": ["l1","l1","l1","l2","l1","l2","l2","l2"],
    "event_type": ["entry","exit","entry","entry","exit","entry","exit","entry"],
    "event_time": [
        "2026-02-09T07:30:00Z",
        "2026-02-09T08:45:00Z",
        "2026-02-09T09:00:00Z",
        "2026-02-09T10:15:00Z",
        "2026-02-10T08:00:00Z",
        "2026-02-10T09:30:00Z",
        "2026-02-10T11:00:00Z",
        "2026-02-10T12:00:00Z"
    ]
})


#Your Task
#Produce a DataFrame with one row per day and location, containing:
#day (YYYY-MM-DD)
#location_id
#total_events → total number of events
#unique_devices → number of distinct devices that generated events

#Rules
#Ignore rows where device_id or event_time is null
#Convert event_time to datetime
#Group by day + location_id
#Sort by day, then location_id

import pandas as pd 

df["event_type"] = df["event_type"].str.lower().str.strip()

df["event_time"] = pd.to_datetime(df["event_time"], utc=True, errors="coerce")


mask = (
  (df["device_id"].notna()) & 
  (df["event_time"].notna()) 
)

df_clean = df[mask].copy()

df_clean["day"] = df_clean["event_time"].dt.strftime("%Y-%m-%d")

df_summary = (
  df_clean
  .groupby(["day", "location_id"], as_index=False)
  .agg(
    total_events=("event_time", "count"),
    unique_devices=("device_id", "nunique")),
  .sort_values(["day", "location_id"]),
  .reset_index(drop=True)
)

df_clean, df_summary 






Keep the output clean (no index columns)
